name: Build and Test - Compiler Zoo

on: [pull_request, workflow_dispatch] 

env:
  GH_ACTIONS_TOOLCHAIN: .github/workflows/toolchains/gh-actions.cmake

jobs:
  release_build:
    runs-on: ubuntu-latest
    container:
        image: dbwy/compiler-zoo
    strategy:
      matrix:
        compiler: [ {suite: gnu, version: 12}, {suite: llvm, version: 14} ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Compiler 
      shell: bash
      run: $GITHUB_WORKSPACE/.github/workflows/scripts/compiler_setup.sh 
           ${{matrix.compiler.suite}} ${{matrix.compiler.version}}

    - name: Setup Build Type
      shell: bash
      run: echo "set(CMAKE_BUILD_TYPE Release CACHE BOOL \"\" FORCE)" >> 
             ${GITHUB_WORKSPACE}/${GH_ACTIONS_TOOLCHAIN}


    - name: Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
                 -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install 
                 -DCMAKE_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/${GH_ACTIONS_TOOLCHAIN}

    - name: Build
      shell: bash
      run: cmake --build ${{runner.workspace}}/build -j2 

    - name: Test
      shell: bash
      run: cmake --build ${{runner.workspace}}/build --target test
